### ISSUE TITLE
TypeError in method with enum argument

### ISSUE THREAD

**Issue by Watchballs** [swig/swig#1026]
test_enum.i:
`enum {
  TEST_ENUM = 'A'
 };`

`$swig -python test.i
 test.i:3: Error: Type error. Expecting an int `

Same thing happens for php and I assume all others...

This is with the release version of 3.0.12. It worked fine in 2.0.1.

**Comment by ojwb** [comment]
And what does `test.i` contain?

**Comment by Watchballs** [comment]
Nothing significant exept this.

**Comment by ojwb** [comment]
You've now changed the text of your report - it was originally showing us `test_enum.i` but that now says `test.i`.

However, that's still clearly not the `test.i` you actually got that error from, as it has just one line but SWIG is reporting an error on line 3.  I'd say the line on which the error occurred is quite likely to be significant here...

If I try your reproducer, it doesn't reproduce the reported problem:

{{{
$ cat test.i
enum { TEST_ENUM = 'A' };
$ swig -python test.i
No module name specified using %module or -module.
$ swig -python -module test test.i
$
}}}

**Comment by Watchballs** [comment]
Ok, I will show you all files in my test suite...
test.i:
`%module test

%{
#include "test.h"
%}

%include "test.h"`

test.h:
`enum numeric { ONE, TWO, THREE };
enum character { CHARACTER = 'c' };

void enum_test_numeric(numeric c);
void enum_test_character(character c); `

test.cpp:
`#include "test.h"
#include <stdio.h>

void enum_test_numeric(numeric c) {
  if (c == ONE) {
    printf("number = ONE ");
  } else if (c == TWO) {
    printf("number = TWO ");
  } else if (c == THREE) {
    printf("number = THREE ");
  } else {
    printf("number = Unknown number! ");
  }
}

void enum_test_character(numeric c) {
  if (c == CHARACTER) {
    printf("character = 'c' ");
  }
  else {
    printf("character = Unknown character! ");
  }
}`

runme.py:
`import test

# ----- Object creation -----

# Print out the value of some enums
print "*** number ***"
print "    ONE    =", test.ONE
print "    TWO   =", test.TWO
print "    THREE  =", test.THREE

print "*** character ***"
print "    CHARACTER    =", test.CHARACTER

print "\nTesting use of numeric enums\n"

test.enum_test_numeric(test.ONE)
test.enum_test_numeric(test.TWO)
test.enum_test_numeric(test.THREE)
test.enum_test_numeric(1234)

print "\nTesting use of character enums\n"
test.enum_test_character(test.CHARACTER)
test.enum_test_character('u')`

After compile and run runme.py:
`TypeError: in method 'enum_test_character' argument 1
of type 'character'` 
It means that is function expecting int's, but swig wraps argument type to char.

**Comment by Watchballs** [comment]
/////////////////////////////////////////////////////
runme.py:
/////////////////////////////////////////////////////
import test

print "*** number ***"
print "    ONE    =", test.ONE
print "    TWO   =", test.TWO
print "    THREE  =", test.THREE

print "*** character ***"
print "    CHARACTER    =", test.CHARACTER

print "\nTesting use of numeric enums\n"

test.enum_test_numeric(test.ONE)
test.enum_test_numeric(test.TWO)
test.enum_test_numeric(test.THREE)
test.enum_test_numeric(1234)

print "\nTesting use of character enums\n"
test.enum_test_character(test.CHARACTER)
test.enum_test_character('u')`
/////////////////////////////////////////////////////
After compile and run runme.py:
`TypeError: in method 'enum_test_character' argument 1
of type 'character'` 
It means that is function expecting int's, but swig wraps argument type to char.

**Comment by Watchballs** [comment]
Ok. If you make little changes in file `examples/python/enum/example.h`, just add char constant to the one of enum elements like:

And then make a wrap, compile _example.so and run `$python runme.py`, You will get:
*** color ***
    RED    = 0
    BLUE   = 1
    GREEN  = g

*** Foo::speed ***
    Foo_IMPULSE   = 0
    Foo_WARP      = 1
    Foo_LUDICROUS = 2

Testing use of enums with functions

color = RED, speed = IMPULSE speed
color = BLUE, speed = WARP speed
Traceback (most recent call last):
  File "runme.py", line 22, in <module>
    example.enum_test(example.GREEN, example.Foo.LUDICROUS)
TypeError: in method 'enum_test', argument 1 of type 'color'

It is strange situation, isn't it?

**Comment by ojwb** [comment]
Thanks.

`git bisect` shows this is an 6 year old regression in commit b13ec94386c8055e9dcc0fb6338b2e3e1e4048d4:

```
    SF bug #3195112 - fix wrapping of enums that are type char
    
    git-svn-id: https://swig.svn.sourceforge.net/svnroot/swig/trunk@12557 626c5289-ae23-0410-ae9c-e8d60b6d4f22
```

Perhaps this change should be limited to statically typed languages.

It seems reasonable on the surface to wrap them as strings in Python, but that means that input typemaps need to accept single character strings and map them to their integer values, which would affect how a wrapper with an overload on an `enum` and `const char *` works.

@wsfulton Thoughts?

**Comment by luav** [comment]
Probably, there is no sense to perform enum values conversion to anything except the base type of the enum (int or another explicitly specified **integral type**). And even such conversion is required only in case enum flags are used as bit masks (which is a pretty common usage in the low-level code).

In the example above the definition is:
```c++
enum numeric { ONE, TWO, THREE };
enum character { CHARACTER = 'c' };

void enum_test_numeric(numeric c);
void enum_test_character(character c);
```
where is the Python call is:
```python
test.enum_test_character(test.CHARACTER)
test.enum_test_character('u')
```
the last call `test.enum_test_character('u')` is made with the invalid type (`str` instead of the `enum character`), so the failed compilation is expected.

**Comment by ojwb** [comment]
Still reproducible with git master (by added `= 'g'` to `examples/python/enum/example.h` as described above).

A workaround if you can modify the header is to add an explicit cast to int, i.e.:

```
enum color { RED, BLUE, GREEN = (int)'g' };
```

Output on `make -C Examples/python/enum` is then:

```
*** color ***
    RED    = 0
    BLUE   = 1
    GREEN  = 103

*** Foo::speed ***
    Foo_IMPULSE   = 0
    Foo_WARP      = 1
    Foo_LUDICROUS = 2

Testing use of enums with functions

color = RED, speed = IMPULSE speed
color = BLUE, speed = WARP speed
color = GREEN, speed = LUDICROUS speed
color = Unknown color!, speed = Unknown speed!

Testing use of enum with class method
IMPULSE speed
WARP speed
LUDICROUS speed
```

**Comment by jschueller** [comment]
likely fixed in 16680f59d

**Comment by ojwb** [comment]
> likely fixed in 16680f5

That seems really unlikely as that commit only changes the scanner, and only for octal and binary literals.

I checked and the testcase as described above still fails with current git master (f3f7fd641407d422330709391738e7b912398190):

```
$ git diff
diff --git a/Examples/python/enum/example.h b/Examples/python/enum/example.h
index 525d62af..8cd3b062 100644
--- a/Examples/python/enum/example.h
+++ b/Examples/python/enum/example.h
@@ -1,6 +1,6 @@
 /* File : example.h */
 
-enum color { RED, BLUE, GREEN };
+enum color { RED, BLUE, GREEN = 'g' };
 
 class Foo {
  public:
$ make -sC Examples/python/enum
*** color ***
    RED    = 0
    BLUE   = 1
    GREEN  = g

*** Foo::speed ***
    Foo_IMPULSE   = 0
    Foo_WARP      = 1
    Foo_LUDICROUS = 2

Testing use of enums with functions

color = RED, speed = IMPULSE speed
color = BLUE, speed = WARP speed
Traceback (most recent call last):
  File "/home/olly/git/swig/Examples/python/enum/runme.py", line 22, in <module>
    example.enum_test(example.GREEN, example.Foo.LUDICROUS)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/olly/git/swig/Examples/python/enum/example.py", line 84, in enum_test
    return _example.enum_test(c, s)
           ~~~~~~~~~~~~~~~~~~^^^^^^
TypeError: in method 'enum_test', argument 1 of type 'color'
make[1]: *** [../../Makefile:1385: python_run] Error 1
make: *** [Makefile:10: check] Error 2
```
