### ISSUE TITLE
cmake build includes disabled backends

### ISSUE THREAD

**Issue by ojwb** [swig/swig#2008]
I noticed that the cmake build include at least chicken, but the standard build doesn't (it was disabled for #1447).

If we're going to have a secondary build system it really needs to be consistent about such things or it'll increase support load.

**Comment by ojwb** [comment]
4.5 months and no response - is nobody actually interested in maintaining the cmake support?

**Comment by ojwb** [comment]
@jschueller @xantares You both seem to have touched the cmake support this year - are either of you interested in maintaining it?

**Comment by jschueller** [comment]
actually I dont see chicken files or any of the removed languages anywere, maybe this was already fixed ?

**Comment by ojwb** [comment]
Oh yes, chicken was removed since.

However, that doesn't fix the underlying issue with the cmake build system here - i.e. that it seems to just build any source files which are present.  The same issue is presumably current if you substitute CFFI for Chicken, and even once CFFI either gets reinstated or removed it would still be wrong even if not currently actually manifesting.  It should only use the source files listed in `eswig_SOURCES` in `Source/Makefile.am`.

**Comment by jschueller** [comment]
we could explicitely list them in the CMakeLists too then

**Comment by ojwb** [comment]
Pulling the list out from where it already is would be better - duplicating the list is a recipe for having updates only applied to one version.

**Comment by ojwb** [comment]
This bug still seems to exist:

```
file (GLOB DOH_SOURCES ${SWIG_SOURCE_DIR}/DOH/*.c)
file (GLOB CPARSE_SOURCES ${SWIG_SOURCE_DIR}/CParse/*.c)
list (REMOVE_ITEM CPARSE_SOURCES ${SWIG_SOURCE_DIR}/CParse/parser.c)
list (APPEND CPARSE_SOURCES)
file (GLOB PREPROCESSOR_SOURCES ${SWIG_SOURCE_DIR}/Preprocessor/*.c)
file (GLOB CORE_SOURCES ${SWIG_SOURCE_DIR}/Swig/*.c)
file (GLOB DOXYGEN_SOURCES ${SWIG_SOURCE_DIR}/Doxygen/*.cxx)
file (GLOB MODULES_SOURCES ${SWIG_SOURCE_DIR}/Modules/*.cxx)
```

**Comment by jschueller** [comment]
which files are you refering to ? I dont see any chicken.cxx Module

**Comment by ojwb** [comment]
I think right now it's a latent bug as right now we don't have any disabled target languages (cffi would have been incorrectly built by cmake too also got removed in cea25abca535fa27b89eedaf2dd978991b42e1a5).

However next time a target language gets disabled like this it will continue to be built by default by cmake.
