### ISSUE TITLE
 Error: Syntax error in input(1) when packaging template

### ISSUE THREAD

**Issue by cbldlpl** [swig/swig#2746]
in .hpp file:
```
namespace xx
{#ifndef AA_H_
#define AA_H_
template<typename T, typename = void>
struct isType : std::false_type{};
#endif // AA_H_
}
```
appears error: Syntax error in input(1).--line of "template<typename T, typename = void>"
I'm really confused and anxiously waiting for a reply.Thks！

**Comment by ojwb** [comment]
This was fixed by the recently released SWIG 4.2.0 so you should upgrade.

**Comment by cbldlpl** [comment]
hello，The version used is 4.2.0, but this error still occurs. I used a clean server environment and I only installed 4.2.0

> This was fixed by the recently released SWIG 4.2.0 so you should upgrade.

**Comment by ojwb** [comment]
Works for me:

```
$ cat test.i
%module x
%inline %{
namespace xx
{
#ifndef AA_H_
#define AA_H_
template<typename T, typename = void>
struct isType : std::false_type{};
#endif // AA_H_
}
%}
$ ../preinst-swig -c++ -python test.i
$ swig -c++ -python test.i
test.i:7: Error: Syntax error in input(1).
```

Here `../preinst-swig` is SWIG 4.2.0 and `swig` is Debian's packaged version of SWIG 4.1.0.

**Comment by cbldlpl** [comment]
Thanks for the reply, but maybe I'm missing something? I used 4.2.0 and still have this problem, the original file is Utils.hpp, I will use %include "Utils.i" in another total i file.this is my Utils.i file, neither of these works:
```
%inline %{
namespacexx
{
#ifndef AA_H_
#define AA_H_
template<typename T, typename = void>
struct isType : std::false_type{};
#endif // AA_H_
}
%}
%{
#include "Utils.hpp"
#include <sstream>

%}

%include "Utils.hpp"
%include "std_string.i"
%include "std_vector.i"
```

or
``` 
%{
#include "Utils.hpp"
#include <sstream>

%}
%inline %{
namespacexx
{
#ifndef AA_H_
#define AA_H_
template<typename T, typename = void>
struct isType : std::false_type{};
#endif // AA_H_
}
%}
%include "Utils.hpp"
%include "std_string.i"
%include "std_vector.i"
```
This is the command line output:
`swig-version`
```
SWIG Version 4.2.0

Compiled with g++ [x86_64-pc-linux-gnu]

Configured options: +pcre

Please see https://www.swig.org for reporting bugs and further information
```

**Comment by cbldlpl** [comment]
I will minimize this issue and update later

**Comment by ojwb** [comment]
Missing space in `namespacexx`?

If not that then minimising a reproducer would be helpful.
