### ISSUE TITLE
testsuite failures with Ruby 3.1.5 and 3.2.3

### ISSUE THREAD

**Issue by ojwb** [swig/swig#2800]
The ruby3.2 job is failing in CI.  It's failed two runs in a row, starting c60734add6eefc343db8a59f3b8155a74305eac7 which doesn't seem a likely culprit and CI passed for its parent commit.

I can reproduce it failing locally, though the error I get seems to be in a different testcase:

```
checking ruby testcase import_fragments (with run test)
<internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:151:in `require': machine stack overflow in critical region (fatal)
make[1]: *** [Makefile:78: import_fragments.cpptest] Error 1
```

The most recent change to touch ruby-specific code seems to be 8157a83b59660c8a61e4a3086f62b399bc7e0f5a but that passed all CI jobs.

**Comment by wsfulton** [comment]
Probably we should raise a bug report to Ruby about this one, it's seems like a Ruby problem. The only problem is it is an import example, so requires two separate shared objects to recreate and will need quite a bit of work to provide a decent bug report for them.

**Comment by wsfulton** [comment]
Same crash is now affecting our testing with Ruby 3.1.5 (was okay with 3.1.4) so I've pinned CI testing of 3.1 to use 3.1.4 until resolved in b6f7460.

**Comment by ojwb** [comment]
Still happens with Ruby 3.2.5 (the latest release) and 12528200d06a43f10cbe4b77d7f3e0f345cb63e1.  There is a 3.1.6 release but the latest 3.1.x RVM has seems to be 3.1.5 (which still fails).

**Comment by wsfulton** [comment]
Reported to ruby developers, see https://bugs.ruby-lang.org/issues/21276

**Comment by wsfulton** [comment]
The segfault won't be fixed in the 3.1.x nor 3.2.x series, so I have disabled the import_fragment test from running the code that segfaults ruby for these versions.
