### ISSUE TITLE
class template template template c++ -> python

### ISSUE THREAD

**Issue by StefanReinhardt** [swig/swig#624]
I currently tried to swig a c++ class structure which is using a lot of templates. 
Basically I want to swig a class template which inherits from a class  template template.  
Sounds a bit confusing so a short example:

`template<template<template<class> class, class> class Op, template<class> class X, class T>
class C : public Op<X,T>
{
};`

Which causes a syntax error `Error: Syntax error in input(1).`

I have attached a minimal example here [insane_templates.zip](https://github.com/swig/swig/files/157770/insane_templates.zip)

Is this expected behaviour (will not be possible with swig) or is it a bug? 
I expected that to work since class  template templates like 
`template <template<class> class A, class T> 
class B : public A<T>
{};` 

are working for me, when using swig 3.0.5

**Comment by wsfulton** [comment]
It is entirely reasonable to expect any valid standard C++ like this to work. However in reality, only basic template template parameter support is working in SWIG (such as 8f09d00bb0416e4aec163df15fcdcb4f58d47a7e) . Parsing errors are usually fairly easily fixed in parser.y and the aforementioned patch gives a good idea as to where to look. What is your example... a template template template parameter???!

The example in this bug report also contains the rare curiously recurring template pattern (for which I think is supported... certainly simple examples do work such as the one in [curiously_recurring_template_pattern.i](https://github.com/swig/swig/blob/master/Examples/test-suite/curiously_recurring_template_pattern.i).)

**Comment by StefanReinhardt** [comment]
Thank for your fast reply. Yes indeed it's a kind of a template template template parameter. I'm implementing a framework for different kinds of simulation. Therefore I have a "templated inheritance structure" because I wanted to be able to exchange the baseclasses (which need to implement the according interface) at all levels when needed just by a template argument. 
I ended up with such a mess in the core structure. But on the other side it is quite easy to use it in the actual usecases. 
So in my case the class C implements actual operations on sth. where Op defines how these operations are applied to the data, X defines how the data is stored and accessed and T defines which data actually is stored. 
I need to define C as a template in order to use it as a baseclass for a mixin pattern where I can define different operations in different classes and plug them together to an actual solver...
This maybe an unusual edgecase though...

I wanted to avoid storing the data etc as parameter in order to avoid multiple pointer dereferencing. In my tests it seems to be quite faster when designing the classes like in the given example compared to adding them as parameter to the class.

**Comment by prs513rosewood** [comment]
Hi,

I have encountered the same parsing error for the following example:
```c++
template<typename T, int dim> struct Foo {
      template <template <typename, int> class X, typename U>
      void operator+=(X<U, dim> & ref) {}
};
```
whereas:
```c++
template<typename T, int dim> struct Foo {
      template <template <typename> class X, typename U>
      void operator+=(X<U> & ref) {}
};
```
is parsed with no errors. I use swig 3.0.2. This issue being open, I assume it hasn't been solved in recent versions ?

**Comment by ojwb** [comment]
Still reproducible with current git master.

All in one version of the first example:

```
%module test

%inline %{
class CustomAttrs{
public:
	enum dattr1d{pos,vel,someCustomCaseVar, d1dLast};
};

template <class T> 
class A
{
public:
	T attributes;
};

template <template<class> class A, class T> 
class B : public A<T> { };

template<template<template<class> class, class> class Op, template<class> class X, class T>
class C : public Op<X,T> { };

template class A<CustomAttrs>;
template class B<A, CustomAttrs>;
template class C<B, A, CustomAttrs>;
%}

%template(AC) A<CustomAttrs>;
%template(BAC) B<A, CustomAttrs>;
%template(CBAC) C<B, A, CustomAttrs>;
```
